- name: Setup dev machine
  hosts: localhost
  roles:
    - devmachine
  vars:
    ansible_become_user: root
    packages:
      - vim
      - zsh
      - cowsay
      - curl
      - git
      - go
      - python
    python_packages:
      - virtualenv
      - virtualenvwrapper
      - ipython
      - ipdb


